### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by caiguang1997** [dinhngtu/OutlookCloseToMinimize#1]
I guessed put released version into the path "**C:\Program Files\Microsoft Office\root\Office16\ADDINS**". However, my OUTLOOK has something wrong when closing. In fact, it cannot be closed and shows "**Outlook is closing**" all the time. Maybe my action was wrong. Though, I suggest you write a **README.md** so that other freshmen won't get confused when using. Thank you for your open-sourse work. Hope it will be a helpful tool to others.

**Comment by dinhngtu** [comment]
Hi,

Thanks for using my addin. I wrote it for my own use so I never bothered writing a readme.

To use the addin, you'll first need to install the [VSTO runtime](https://www.microsoft.com/en-us/download/details.aspx?id=56961).
Afterwards, extract the zip content to an appropriate directory (not in a temporary directory, since the addin runs in place).
Simply double-click the .vsto file to install.
The addin works best when the "Hide when minimized" option is enabled (by right-clicking Outlook's tray icon):
![image](https://user-images.githubusercontent.com/1257909/134686359-b6df9c6f-364e-4c40-9d9a-ec67cb0fa3bd.png)

If Outlook crashes, you can run `outlook.exe /safe` and remove the addin from Options - Add-ins.
I released [version 1.1](https://github.com/dinhngtu/OutlookCloseToMinimize/releases/tag/1.1) that should fix the crash bug.

I tested the addin with Outlook 365 and .NET 4.7.2, but in theory it should work with older Outlook versions with no problem.
Please feel free to tell me if the addin doesn't work with your system.

**Comment by caiguang1997** [comment]
Really wonderful. It does work! BTW, I'd like to give an advice and hope you can take it into consideration. That's, when we click close, what we virtually want is that don't see the icon but we can see receive new message. Therefore, what shows in picture below is better. Hope you take it into consideration!
![0@ELGUWYQR`TJQB9T6X16_I](https://user-images.githubusercontent.com/30717104/134757852-ce34a769-4f8a-4f9f-aeba-ffb5a2dae730.png)

**Comment by kocane** [comment]
@dinhngtu thanks for this, works well with Office 2021 LTSC.
